accounts:
  - name: alice
    coins: ["1000cheq", "100000000stake"]
  - name: bob
    coins: ["500cheq"]
validator:
  name: alice
  staked: "100000000stake"
client:
  vuex:
    path: "vue/src/store"
faucet:
  name: bob 
  coins: ["5cheq"]
