name: Cheqd Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

workflow_dispatch:

jobs:
  check_links:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out source code
      - uses: actions/checkout@v2
      - name: Check links
      - uses: gaurav-nelson/github-action-markdown-link-check@v1