name: Link Markdown

on:
  push:
    branches: [ test ]
  pull_request:
    branches: [ test ]

jobs:
  check_links:
    name: Links
    runs-on: ubuntu-latest
    steps:
      - name: Actions Checkout
        uses: actions/checkout@v2
      - name: Check Links
        uses: gaurav-nelson/github-action-markdown-link-check@v1
        with: 
          file-extension: '.md'

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.40
          args: --timeout 5m0s
