name: Update-Web-Content

on: 
  push:
    branches:
      - master
  # pull_request:
  #   branches: [ release ]

jobs:
  job1:
    name: Update Web Content
    runs-on: ubuntu-latest
    steps:
    - name: Check-out source code
      uses: actions/checkout@v2
    - name: Install AWS CLI
      uses: chrislennon/action-aws-cli@v1.1
    # - name: Sync web content
    #   run: aws s3 sync ./web-content s3://hello-world.devopscba.com --delete
    #   env:
    #     AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    #     AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    #     AWS_REGION: us-east-1
    - name: List Env
      run:  env

  
